= "Berlin Clock" Code Kata

This kata I found at http://technologyconversations.com/2014/02/25/java-8-tutorial-through-katas-berlin-clock-easy/[Technology Conversations].

== The Berlin Clock

On the top of the clock there is a yellow lamp that blinks on/off every two seconds,
i.e. every even second it is on, every odd second it is off.

The next two rows have each four red lamps. These indicate the hours of a day.
Every lamp in the upper row represents 5 hours. In the lower row
of red lamps, every lamp represents 1 hour. So if two lamps of the first row
and three of the second row are switched on that indicates 5+5+3=13h or 1 pm.

The two rows of lamps at the bottom count the minutes. The first of these
rows has 11 lamps, the second 4. In the first row every lamp represents 5 minutes.
In this first row the 3rd, 6th and 9th lamp are red and indicate the first quarter,
half and last quarter of an hour. The other lamps are yellow. In the last row with
4 lamps, every lamp represents 1 minute.

The lamps are switched on from left to right.

== The assignment

1. Create a representation of the Berlin Clock for a given time (hh::mm:ss).
2. Create a textual representation of the Berlin clock where letters represent the lights,
   their colors and whether their on or off.
+
For example:
+
....
Y
RR00
RRRR
YYYRYYYRYYYRY000
0000
....
+
Represents 14:50 and some even second.
